<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503193533 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE billing_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5B3C16CA76ED395 ON billing_transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_F5B3C16C591CC992 ON billing_transaction (course_id)');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F5B3C16CA76ED395 FOREIGN KEY (user_id) REFERENCES billing_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE billing_transaction ADD CONSTRAINT FK_F5B3C16C591CC992 FOREIGN KEY (course_id) REFERENCES billing_course (id)');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT fk_723705d1a76ed395');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT fk_723705d1591cc992');
        $this->addSql('DROP TABLE transaction');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, course_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_723705d1a76ed395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX idx_723705d1591cc992 ON transaction (course_id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT fk_723705d1a76ed395 FOREIGN KEY (user_id) REFERENCES billing_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT fk_723705d1591cc992 FOREIGN KEY (course_id) REFERENCES billing_course (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F5B3C16CA76ED395');
        $this->addSql('ALTER TABLE billing_transaction DROP CONSTRAINT FK_F5B3C16C591CC992');
        $this->addSql('DROP TABLE billing_transaction');
    }
}
